# Generated by Django 5.1 on 2024-09-29 00:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_product_stripe_price_id_product_stripe_product_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='stripe_price_id',
        ),
        migrations.RemoveField(
            model_name='product',
            name='stripe_product_id',
        ),
    ]
