# Generated by Django 5.1 on 2025-07-20 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_productgallery'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productgallery',
            options={'verbose_name': 'photogallery', 'verbose_name_plural': 'product gallery'},
        ),
    ]
